#数据库信息配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qk
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

# mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置数据库sql执行信息(日志)
    map-underscore-to-camel-case: true # 添加驼峰命名映射
  mapper-locations: classpath:mapper/*.xml # 如果没有按照xml配置文件的三个规范走,就得单独配置xml映射文件去找

#阿里云oss配置参数
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-web-oss123
    region: cn-beijing
